### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by mochechan** [sivann-tw/hiver-iot-kit-ble#2]
$ sudo node app.js 
/home/pi/hiver-iot-kit-ble/node_modules/ble-shepherd/node_modules/cc-bnp/node_modules/serialport/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/hiver-iot-kit-ble/node_modules/ble-shepherd/node_modules/cc-bnp/node_modules/serialport/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/hiver-iot-kit-ble/node_modules/ble-shepherd/node_modules/cc-bnp/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:570:32)

**Comment by coold8d** [comment]
@mochechan If you've upgraded node then `npm rebuild` might fix this for you.
If still not working, Try `rm -r node_modules` then `npm install ` should fix your problem.
